from django.http import JsonResponse


def get_data(request):
    data = [
        {
            "id": 1,
            "title": "چیپس سیب زمینی نمکی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/e01173ed-b86a-4bfa-8384-6b24dec727b7.jpg",
            "price": 20000,
            "category": "تنقلات",
            "SubCategorization": "چیپس و پفک",
            "brand": "چیپسینو",
            "brandLatinName": "Chipsino",
            "available": "true",

        },
        {
            "id": 2,
            "title": "پفک پنیری",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/12575.png",
            "price": 15000,
            "category": "تنقلات",
            "SubCategorization": "چیپس و پفک",
            "brand": "پفکین",
            "brandLatinName": "Pofakin",
            "available": "true",
        },
        {
            "id": 3,
            "title": "بیسکوییت شکلاتی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/389962.png",
            "price": 30000,
            "category": "تنقلات",
            "SubCategorization": "بیسکوییت و ویفر و کراکر",
            "brand": "شیرین عسل",
            "brandLatinName": "Shirin Asal",
            "available": "true",
        },
        {
            "id": 4,
            "title": "پنیر سفید صبحانه",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/387470.png",
            "price": 80000,
            "category": "لبنیات",
            "SubCategorization": "پنیر",
            "brand": "کاله",
            "brandLatinName": "Kalleh",
            "available": "true",
        },
        {
            "id": 5,
            "title": "شیر کم‌چرب 1.5 لیتری",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/437288.png",
            "price": 25000,
            "category": "لبنیات",
            "SubCategorization": "شیر",
            "brand": "پگاه",
            "brandLatinName": "Pegah",
            "available": "true",
        },
        {
            "id": 6,
            "title": "چای سیاه عطری",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/46138.png",
            "price": 120000,
            "category": "نوشیدنی ها",
            "SubCategorization": "چای",
            "brand": "گلستان",
            "brandLatinName": "Golestan",
            "available": "true",
        },
        {
            "id": 7,
            "title": "نوشابه کولا 1.5 لیتری",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/429667.png",
            "price": 15000,
            "category": "نوشیدنی ها",
            "SubCategorization": "نوشابه",
            "brand": "کوکاکولا",
            "brandLatinName": "Coca-Cola",
            "available": "true",
        },
        {
            "id": 8,
            "title": "ویفر کاکائویی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/223389.png",
            "price": 25000,
            "category": "تنقلات",
            "SubCategorization": "بیسکوییت و ویفر و کراکر",
            "brand": "ویتانا",
            "brandLatinName": "Vitana",
            "available": "true",
        },
        {
            "id": 9,
            "title": "کیک کاکائویی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/470507.png",
            "price": 40000,
            "category": "تنقلات",
            "SubCategorization": "کیک و کلوچه",
            "brand": "کیکین",
            "brandLatinName": "Cakein",
            "available": "true",
        },
        {
            "id": 10,
            "title": "شکلات تلخ 84 درصد",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/450928.png",
            "price": 50000,
            "category": "تنقلات",
            "SubCategorization": "شکلات و آبنبات",
            "brand": "باراکا",
            "brandLatinName": "Baraka",
            "available": "true",
        },
        {
            "id": 11,
            "title": "آبنبات نعنا",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/365690.png",
            "price": 10000,
            "category": "تنقلات",
            "SubCategorization": "شکلات و آبنبات",
            "brand": "نعنایی",
            "brandLatinName": "Nanaei",
            "available": "true",
        },
        {
            "id": 12,
            "title": "لواشک میوه‌ای",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/387974.png",
            "price": 15000,
            "category": "تنقلات",
            "SubCategorization": "لواشک و آلوچه",
            "brand": "ترشک",
            "brandLatinName": "Torshak",
            "available": "true",
        },
        {
            "id": 13,
            "title": "پاستیل خرسی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/386709.png",
            "price": 35000,
            "category": "تنقلات",
            "SubCategorization": "پاستیل و آدامس",
            "brand": "ژلاتینو",
            "brandLatinName": "Gelatino",
            "available": "true",
        },
        {
            "id": 14,
            "title": "پودر ژله آلبالو",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/344332.png",
            "price": 20000,
            "category": "تنقلات",
            "SubCategorization": "پودر کیک و ژله و دسر",
            "brand": "ژله‌ساز",
            "brandLatinName": "Jelehsaz",
            "available": "true",
        },
        {
            "id": 15,
            "title": "دسر شکلاتی آماده",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/345097.png",
            "price": 30000,
            "category": "تنقلات",
            "SubCategorization": "دسر های آماده",
            "brand": "شیرین‌پارس",
            "brandLatinName": "Shirin Pars",
            "available": "true",
        },
        {
            "id": 16,
            "title": " گز پسته‌ای",
            "imageSrc": "https://shiringaz.com/media/shiringaz/2020/01/14.jpg",
            "price": 60000,
            "category": "تنقلات",
            "SubCategorization": "نقل و گز",
            "brand": "گز اصفهان",
            "brandLatinName": "Gaz Esfahan",
            "available": "true",
        },
        {
            "id": 17,
            "title": "ماست موسیر",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/414254.png",
            "price": 35000,
            "category": "لبنیات",
            "SubCategorization": "ماست",
            "brand": "هراز",
            "brandLatinName": "Haraz",
            "available": "true",
        },
        {
            "id": 18,
            "title": "دوغ گازدار 1.5 لیتری",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/393498.png",
            "price": 30000,
            "category": "لبنیات",
            "SubCategorization": "دوغ",
            "brand": "دامداران",
            "brandLatinName": "Damdaran",
            "available": "true",
        },
        {
            "id": 19,
            "title": "خامه صبحانه",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/4543a4d9-3bc3-47e7-9987-f2908717575f.jpg",
            "price": 40000,
            "category": "لبنیات",
            "SubCategorization": "خامه",
            "brand": "میهن",
            "brandLatinName": "Mihan",
            "available": "true",
        },
        {
            "id": 20,
            "title": "کشک پاستوریزه",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/435205.png",
            "price": 35000,
            "category": "لبنیات",
            "SubCategorization": "کشک",
            "brand": "سحر",
            "brandLatinName": "Sahar",
            "available": "true",
        },
        {
            "id": 21,
            "title": "کره محلی 100 گرمی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/502496.png",
            "price": 50000,
            "category": "لبنیات",
            "SubCategorization": "کره",
            "brand": "روستایی",
            "brandLatinName": "Rostaei",
            "available": "true",
        },
        {
            "id": 22,
            "title": "بستنی وانیلی",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/542f776f-640f-4558-a645-bfce39666c6a.jpg",
            "price": 25000,
            "category": "لبنیات",
            "SubCategorization": "بستنی",
            "brand": "دومینو",
            "brandLatinName": "Domino",
            "available": "true",
        },
        {
            "id": 23,
            "title": "دمنوش نعناع",
            "imageSrc": "https://statics.basalam.com/public-18/users/l7g8Z/04-06/xV1jgoiEwXUaUdxHRbEc45mYVzU2jtc9QAxfze9g7ZRyZFT6tG.jpg_512X512X70.jpg",
            "price": 70000,
            "category": "نوشیدنی ها",
            "SubCategorization": "دمنوش",
            "brand": "چای‌ساز",
            "brandLatinName": "Chaisaz",
            "available": "true",
        },
        {
            "id": 24,
            "title": "پودر قهوه اسپرسو",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/399013.png",
            "price": 140000,
            "category": "نوشیدنی ها",
            "SubCategorization": "پودر قهوه",
            "brand": "لامبورگینی",
            "brandLatinName": "Lamborghini",
            "available": "true",
        },
        {
            "id": 25,
            "title": "قهوه فوری کلاسیک",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/381808.png",
            "price": 130000,
            "category": "نوشیدنی ها",
            "SubCategorization": "قهوه فوری",
            "brand": "نسکافه",
            "brandLatinName": "Nescafe",
            "available": "true",
        },
        {
            "id": 26,
            "title": "آب معدنی کوچک",
            "imageSrc": "https://asset.okala.com/unsigned/rs:fill/size:0:0/plain/s3://cdn//product/412775.png",
            "price": 5000,
            "category": "نوشیدنی ها",
            "SubCategorization": "آب معدنی",
            "brand": "دماوند",
            "brandLatinName": "Damavand",
            "available": "true",
        }
    ];

    limit = request.GET.get('limit')

    # If 'limit' is provided, convert it to an integer and limit the data
    if limit:
        try:
            limit = int(limit)
            data = data[:limit]
        except ValueError:
            return JsonResponse({"error": "Invalid limit value"}, status=400)

    return JsonResponse(data, safe=False)
